HOSTS:
  master:
    roles:
      - master
      - agent
    platform: el-6-i386
    hypervisor: vcloud
    template: Delivery/Quality Assurance/Templates/vCloud/redhat-6-i386
  agent:
    roles:
      - agent
    platform: windows-2003r2-32
    hypervisor: vcloud
    template: Delivery/Quality Assurance/Templates/vCloud/win-2003r2-i386
CONFIG:
  filecount: 12
  datastore: instance0
  resourcepool: delivery/Quality Assurance/FOSS/Dynamic
  folder: Delivery/Quality Assurance/FOSS/Dynamic
